### ISSUE TITLE
View Profile

### ISSUE THREAD

**Issue by jayjmanley** [cs130-w21/3#10]
## User Story
As a user, I would like to view my profile so that I can see my personal information.

## Detailed Description
When on the profile tab, the user should be able to see their account information.

## Acceptance Criteria
- [x] Given the user is logged in, then the tab should show their relevant information from the database.

## Tasks
- [x] Create Profile tab on frontend #97 
- [x] Populate tab with information held in local storage #98

**Comment by mfarber99** [comment]
Merging this story with others
