### ISSUE TITLE
Edit Profile

### ISSUE THREAD

**Issue by jayjmanley** [cs130-w21/3#11]
## User Story
As a user, I would like to edit my profile so that I can change my personal information.

## Detailed Description
When on the profile tab, the user should be able to edit their account information.

## Acceptance Criteria
- [ ] Given the user is logged in, then on the profile tab they should be able to click an edit button.
- [ ] Given the user clicked the edit button, a popup modal should display asking what changes should be made.
- [ ] Given the user saves the changes, both the database table and local storage should be updated with the new information. 

## Tasks
- [ ] Create edit button and popup modal for editable profile information #99 
- [ ] Update Account DAO and Controller to have an update API for account information #101  
- [ ] Update information in local storage to be accurate #102

**Comment by mfarber99** [comment]
No longer doing this
