### ISSUE TITLE
Sign up, Login, Logout

### ISSUE THREAD

**Issue by jayjmanley** [cs130-w21/3#15]
## User Story
As a user, I would like to create an account, log into it, and log out of it so that I can have access to the app, view my profile and friends. 

## Detailed Description
The user should be able to create an account with personal info and access that account by logging in and out when desired. When users open the web page and have been previously logged in, they should not have to login again, same with refreshing the page. 

## Acceptance Criteria
- [x] Given the user is not logged in, they should be directed to the login page.
- [x] Given the user does not have an account, they should be able to go to the signup page to make an account.
- [x] Given the user is logged in, they should be able to logout. 
- [x] Given the user is logged in, closes the tab, and reopens it, they should still be logged in (same with refresh). 

## Tasks
- [x] Create login, signup, and logout UI #91 
- [x] Create DynamoDB table for accounts  in AWS console #92 
- [x] Create Account model class for entities, AccountDao class to access DynamoDB for creating account and logging in, and AccountController to call DAO methods with API endpoints #88 
- [x] Call Create and Login Account APIs on frontend to create an account or login #94 
- [x] Save authentication key in local storage with account information #95 
- [x] Clear local storage when logging out #96
