### ISSUE TITLE
Add Friend

### ISSUE THREAD

**Issue by adamgrif** [cs130-w21/3#16]
## User Story
As a user, I would like to add friends so that I can connect with other users on the app and keep them motivated.

## Detailed Description
Users should be able to navigate to the profile page and input another user's email to add them as a friend. If the email is valid (account exists), the friend should appear on the current user's friend list, otherwise an error should be displayed.

## Acceptance Criteria
- [x] Given a user is on the Profile tab, they should be able to input a user's email and click a button to add a friend.
- [x] Given a user inputs a valid email and clicks the add button, their friends list should be updated to include the new friend.
- [x] Given a user inputs an invalid email and clicks the add button, an error should popup.

## Tasks
- [x] Create text input and add button on Profile tab to add friend #112 
- [x] Update Account DAO and Controller to add and remove friends with new API endpoints #113 
- [x] Call Add/Remove Friend APIs on frontend #114 
- [x] Update local storage to have accurate list of friends on success #115
