### ISSUE TITLE
View Friend's Workouts

### ISSUE THREAD

**Issue by mfarber99** [cs130-w21/3#18]
## User Story
As a user, I would like to view my friends' workouts and their corresponding exercises so that I can discover new ones (of the latter two) I like.

## Detailed Description
When on the Friends tab, the user should be able to see all of their friends and their corresponding workouts with exercises.

## Acceptance Criteria
- [x] Given a user is logged in, there should be a Friends tab to see friends' workouts.
- [x] Given a user is on the Friends tab, it should be populated with all of their friends' workout tables.

## Tasks

- [x] Create Friends tab on front end #116
- [x] Populate tab with user friend's list from local storage #117 
- [x] Retrieve friends workouts and exercises from backend #118 
- [x] Display friend workouts in corresponding tables #120
