### ISSUE TITLE
Save Workout

### ISSUE THREAD

**Issue by mfarber99** [cs130-w21/3#19]
## User Story
As a user, I would like to save workouts/exercises from my friends so that I can easily add ones I like to my list.

## Detailed Description
Users should be able to navigate to the Friends tab and click a save label next to a workout in a friend's workouts table causing the workout and exercises with it saved to the user's list.

## Acceptance Criteria
- [x] Given a user goes to the Friends tab, there should be a save label next to a friend's workout.
- [x] Given a user clicks the save label next to a workout, the workout and exercises in it should be saved to the user's list.

## Tasks
- [x] Create save label next to friend's workouts #122 
- [x] Call Create Exercise and Create Workout APIs when save label clicked on frontend #123
