### ISSUE TITLE
View Workouts

### ISSUE THREAD

**Issue by mfarber99** [cs130-w21/3#2]
## User Story
As a user, I would like to view my workouts so that I know which one to do on a certain day.

## Detailed Description
When on the workouts tab, the user should be able to see a list of their workouts at the top of the page in a calendar format.

## Acceptance Criteria
- [x] Given the user has no workouts, then the calendar should be empty with messages to add a new workout. 
- [x] Given the user has workouts, then the calendar should display them to the user with their information.

## Tasks
- [x] Create Full-Calendar on frontend #62 
- [x] Create Workout table on the frontend #76 
- [x] Create DynamoDB table for workouts in AWS console #64 
- [x] Create Workout model class for entities, WorkoutDao class to access DynamoDB, and WorkoutController to call DAO method and create API endpoint for GET operation #66 
- [x] Call GET Workouts API on frontend to populate calendar #68
