### ISSUE TITLE
Update Exercise

### ISSUE THREAD

**Issue by mfarber99** [cs130-w21/3#21]
## User Story
As a user, I would like to update an exercise so that I can change its relevant information to be more current (i.e. change the sets, reps, weight, etc.).

## Detailed Description
When on the workouts tab, the user should be able to update an exercise on their list of exercises by clicking an edit label, filling out information in a popup modal, and clicking "update" once they are done.

## Acceptance Criteria
- [x] Given the user clicks on the update exercise label, a popup modal form should be displayed asking for the changes to be made.
- [x] Given the user fills out all the relevant changes they want and clicks "save", the updated exercise should now be displayed on their list at the bottom of the page.

## Tasks
- [x] Create edit label and popup modal form on frontend #35 
- [x] Update WeightExerciseDao and RunExerciseDao classes to access DynamoDB for updating new entities #36 
- [x] Update ExerciseController to call new DAO methods and create API endpoints #37 
- [x] Call Update Exercise APIs on frontend #38
