### ISSUE TITLE
Update Workout

### ISSUE THREAD

**Issue by mfarber99** [cs130-w21/3#22]
## User Story
As a user, I would like to update a workout so that I can change its relevant exercises to be more current.

## Detailed Description
When on the workouts tab, the user should be able to update a workout on their planner by clicking an edit label/icon, filling out information in a popup modal, and clicking "update" once they are done.

## Acceptance Criteria
- [x] Given the user clicks on the update workout label, a popup modal form should be displayed asking for the changes to be made.
- [x] Given the user fills out all the relevant changes they want and clicks "save", the updated workout should now be displayed on their planner at the top of the page.

## Tasks
- [x] Create edit label and popup modal form on frontend #70 
- [x] Update WorkoutDao class to access DynamoDB for updating new entities and WorkoutController to call new DAO method with new API endpoint #71 
- [x] Call Update Workout API on frontend #72
