### ISSUE TITLE
Remove Friend

### ISSUE THREAD

**Issue by adamgrif** [cs130-w21/3#23]
## User Story
As a user, I would like to be able to remove friends so that I can stop following people I despise.

## Detailed Description
Users should be able to navigate to the profile page and be able to click a button to delete a friend. There should then be a popup for the user to confirm the deletion.

## Acceptance Criteria
- [x] Given a user is on the Profile tab, they should be able to click a button to delete a friend.
- [x] Given a user clicks the delete button, the user should be able to confirm their request.

## Tasks
- [x] Create delete buttons next to friend emails on the profile tab #119 
- [x] Update local storage to have accurate list of friends on API success #121
