### ISSUE TITLE
Add Workout

### ISSUE THREAD

**Issue by mfarber99** [cs130-w21/3#3]
## User Story
As a user, I would like to be able to add a new workout to my planner so that I can keep track of my workouts and their exercises.

## Detailed Description
When on the workouts tab, the user should be able to add a new workout to their planner by clicking a button, filling out information in a popup modal, and clicking "add" once they are done.

## Acceptance Criteria
- [x] Given the user clicks on the add workout button, a popup modal form should be displayed asking for the relevant workout info.
- [x] Given the popup is open, there should be a list of exercises that can be selected by checkmarks and text inputs for other workout info (e.g. name and days of the week).
- [x] Given the user fills out all the relevant information and clicks "add", the new workout should now be displayed on their planner at the top of the page.

## Tasks
- [x] Create workout add button and popup modal form on frontend #60 
- [x] Update WorkoutDao class to access DynamoDB for adding new entities and WorkoutController to call new DAO method with new API endpoint #61 
- [x] Call Add Workout API on frontend #63
