### ISSUE TITLE
Remove Workout

### ISSUE THREAD

**Issue by mfarber99** [cs130-w21/3#4]
## User Story
As a user, I would like to remove a workout from my planner so that I can have a more up-to-date one.

## Detailed Description
When on the workouts tab, the user should be able to remove a workout from their planner by clicking a remove mark/label on the workout.

## Acceptance Criteria
- [x] Given the user clicks on the remove label, a popup modal should be displayed to confirm the action.
- [x] Given the user confirms the removal and clicks "confirm", the workout should now be removed from their planner at the top of the page.

## Tasks
- [x] Create remove label and popup modal for confirmation on frontend #65 
- [x] Update WorkoutDao class to access DynamoDB for removing entities and WorkoutController to call new DAO method with new API endpoint #67 
- [x] Call Remove Workout API on frontend #69
