### ISSUE TITLE
View Exercises

### ISSUE THREAD

**Issue by mfarber99** [cs130-w21/3#6]
## User Story
As a user, I would like to view my exercises so that I know which ones I have recorded and can add to workouts.

## Detailed Description
When on the workouts tab, the user should be able to see a list of their exercises at the bottom of the page in a table format with all their info displayed. 

## Acceptance Criteria
- [x] Given the user has no exercises, then the table should be empty with messages to add an exercise. 
- [x] Given the user has exercises, then the table should display them to the user with their information row-by-row. 

## Tasks
- [x] Create Material-UI table on frontend #48 
- [x] Create DynamoDB table for exercises in AWS console #49 
- [x] Create ExerciseRun and ExerciseWeight model classes for entities #50 
- [x] Create WeightExerciseDao and RunExerciseDao classes to access DynamoDB #51 
- [x] Create ExerciseController to call DAO methods and create API endpoints #52 
- [x] Call Get Exercise APIs on frontend to populate table #53
