### ISSUE TITLE
Add Exercise

### ISSUE THREAD

**Issue by mfarber99** [cs130-w21/3#7]
## User Story
As a user, I would like to be able to add a new exercise to my list so that I can keep track of their specific information (i.e. sets, reps, weight, distance).

## Detailed Description
When on the workouts tab, the user should be able to add a new exercise to their list of exercises by clicking a button, filling out information in a popup modal, and clicking "add" once they are done.

## Acceptance Criteria
- [x] Given the user clicks on the add exercise button, a popup modal form should be displayed asking for the relevant exercise info.
- [x] Given the popup is open, the first selection should be a dropdown to choose the exercise type as either "Run" or "Weights", which should then change the text inputs for the rest of the modal.
- [x] Given the user fills out all the relevant information and clicks "add", the new exercise should now be displayed on their list at the bottom of the page.

## Tasks
- [x] Create add button and popup modal form on frontend #39 
- [x] Update WeightExerciseDao and RunExerciseDao classes to access DynamoDB for adding new entities #40 
- [x] Update ExerciseController to call new DAO methods and create API endpoints #41 
- [x] Call Add Exercise APIs on frontend #42
