### ISSUE TITLE
Remove Exercise

### ISSUE THREAD

**Issue by mfarber99** [cs130-w21/3#8]
## User Story
As a user, I would like to remove exercises from my list so that I have a more current one.

## Detailed Description
When on the workouts tab, the user should be able to remove an exercise from their list of exercises by clicking a remove label for that exercise on its row in the table. 

## Acceptance Criteria
- [x] Given the user clicks on the remove label, a popup modal should be displayed to confirm the action.
- [x] Given the user confirms the removal and clicks "confirm", the exercise should now be removed from their list at the bottom of the page.

## Tasks
- [x] Create remove label and popup modal for confirmation on frontend #43 
- [x] Update WeightExerciseDao and RunExerciseDao classes to access DynamoDB for removing entities #44 
- [x] Update ExerciseController to call new DAO methods and create API endpoints #45 
- [x] Call Remove Exercise APIs on frontend #46
